### ISSUE TITLE
Scrolling in contact me

### ISSUE THREAD

**Issue by wilsonid** [wilsonid/portfolio-site#15]
Submitter: Tommy
Email: t3dodson@gmail.com
http://www.wilsonid.com/contact/

Not a huge issue but on this page on my 1920x1080 monitor the contact page scrolls. It would look better if it was fixed to maximum the height of the screen.

**Comment by wilsonid** [comment]
Resolved: changed text from 20 to 18px and line height to 1.25em

**Comment by t3dodson** [comment]
welcome...
